version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: resume-chatbot-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BACKEND_PORT=8000
      # - CORS_ORIGINS=["http://localhost:3000", "http://frontend:3000","http://207.148.121.83:3000"]
      - RESUME_DATA_PATH=./backend/data/resume.json
      - DEBUG=false
      - LOG_LEVEL=info
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend/data:/app/backend/data:ro
    networks:
      - resume-chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: resume-chatbot-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://207.148.121.83:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - resume-chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  widget:
    build:
      context: .
      dockerfile: Dockerfile.widget
    container_name: resume-chatbot-widget
    ports:
      - "3100:80"
    networks:
      - resume-chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  resume-chatbot-network:
    driver: bridge

volumes:
  resume_data:
    driver: local
